BEGIN;

--
-- ACTION ALTER TABLE
--
ALTER TABLE "hayer_refresh_job" ADD COLUMN "planJson" text;

-- Stable wire identity and queryable discovery projections. These stay out of
-- the Serverpod model so the existing catalog persistence SQL remains
-- byte-for-byte unchanged and PostgreSQL owns every derived value.
CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE OR REPLACE FUNCTION hayer_discovery_rating(value jsonb)
RETURNS double precision
LANGUAGE plpgsql
IMMUTABLE STRICT PARALLEL SAFE
AS $$
DECLARE
  parsed numeric;
BEGIN
  IF jsonb_typeof(value) <> 'number' THEN
    RETURN NULL;
  END IF;
  parsed := (value #>> '{}')::numeric;
  IF parsed < 0 OR parsed > 5 THEN
    RETURN NULL;
  END IF;
  RETURN parsed::double precision;
END;
$$;

CREATE OR REPLACE FUNCTION hayer_discovery_review_count(value jsonb)
RETURNS bigint
LANGUAGE plpgsql
IMMUTABLE STRICT PARALLEL SAFE
AS $$
DECLARE
  parsed numeric;
BEGIN
  IF jsonb_typeof(value) <> 'number' THEN
    RETURN NULL;
  END IF;
  parsed := (value #>> '{}')::numeric;
  IF parsed < 0 OR parsed > 9223372036854775807 OR trunc(parsed) <> parsed THEN
    RETURN NULL;
  END IF;
  RETURN parsed::bigint;
END;
$$;

CREATE OR REPLACE FUNCTION hayer_discovery_price_level(value jsonb)
RETURNS smallint
LANGUAGE plpgsql
IMMUTABLE STRICT PARALLEL SAFE
AS $$
DECLARE
  parsed numeric;
BEGIN
  IF jsonb_typeof(value) <> 'number' THEN
    RETURN NULL;
  END IF;
  parsed := (value #>> '{}')::numeric;
  IF parsed < 1 OR parsed > 4 OR trunc(parsed) <> parsed THEN
    RETURN NULL;
  END IF;
  RETURN parsed::smallint;
END;
$$;

-- Mirrors DiscoveryTaxonomyService.normalizeAlias, for Discover type keys and
-- search text: Dart's String.trim, then
-- toLowerCase, then collapsing RegExp(r'\s+') to one space. The classes are
-- spelled out because PostgreSQL's \s and btrim depend on the C library and
-- skip no-break spaces; U+0085 is trimmed at the ends but kept inside, as in
-- Dart.
CREATE OR REPLACE FUNCTION hayer_discovery_normalize(value text)
RETURNS text
LANGUAGE sql
IMMUTABLE STRICT PARALLEL SAFE
AS $$
  SELECT regexp_replace(
    lower(regexp_replace(
      value,
      '^[\u0009-\u000d\u0020\u0085\u00a0\u1680\u2000-\u200a\u2028\u2029\u202f\u205f\u3000\ufeff]+|[\u0009-\u000d\u0020\u0085\u00a0\u1680\u2000-\u200a\u2028\u2029\u202f\u205f\u3000\ufeff]+$',
      '',
      'g'
    )),
    '[\u0009-\u000d\u0020\u00a0\u1680\u2000-\u200a\u2028\u2029\u202f\u205f\u3000\ufeff]+',
    ' ',
    'g'
  )
$$;

-- Folds validated weekly opening periods into week minutes, where Monday
-- 00:00 is 0 and the week has 10,080, using PlaceAvailability.isOpenDuring's
-- overnight rule and its Sunday-to-Monday spill. Null means no valid period:
-- an hours filter fails and Open now is unknown.
CREATE OR REPLACE FUNCTION hayer_discovery_opening_hours(hours jsonb)
RETURNS int4multirange
LANGUAGE plpgsql
IMMUTABLE STRICT PARALLEL SAFE
AS $$
DECLARE
  period jsonb;
  day_number numeric;
  open_minute numeric;
  close_minute numeric;
  day_start integer;
  ranges int4range[] := ARRAY[]::int4range[];
BEGIN
  IF jsonb_typeof(hours) <> 'array' THEN
    RETURN NULL;
  END IF;
  FOR period IN SELECT value FROM jsonb_array_elements(hours) LOOP
    CONTINUE WHEN jsonb_typeof(period) <> 'object'
      OR jsonb_typeof(period -> 'day') IS DISTINCT FROM 'number'
      OR jsonb_typeof(period -> 'openMinutes') IS DISTINCT FROM 'number'
      OR jsonb_typeof(period -> 'closeMinutes') IS DISTINCT FROM 'number'
      OR jsonb_typeof(period -> 'overnight') IS DISTINCT FROM 'boolean';
    day_number := (period ->> 'day')::numeric;
    open_minute := (period ->> 'openMinutes')::numeric;
    close_minute := (period ->> 'closeMinutes')::numeric;
    CONTINUE WHEN day_number < 1 OR day_number > 7
      OR trunc(day_number) <> day_number
      OR open_minute < 0 OR open_minute > 1439
      OR trunc(open_minute) <> open_minute
      OR close_minute < 0 OR close_minute > 1440
      OR trunc(close_minute) <> close_minute;
    day_start := (day_number::integer - 1) * 1440;
    IF (period ->> 'overnight')::boolean
      OR (close_minute <= open_minute AND close_minute <> 1440) THEN
      ranges := ranges || int4range(day_start + open_minute::integer, day_start + 1440);
      ranges := ranges || CASE
        WHEN day_number = 7 THEN int4range(0, close_minute::integer)
        ELSE int4range(day_start + 1440, day_start + 1440 + close_minute::integer)
      END;
    ELSE
      ranges := ranges || int4range(
        day_start + open_minute::integer,
        day_start + close_minute::integer
      );
    END IF;
  END LOOP;
  IF cardinality(ranges) = 0 THEN
    RETURN NULL;
  END IF;
  RETURN int4multirange(VARIADIC ranges);
END;
$$;

ALTER TABLE "hayer_poi_catalog"
  ADD COLUMN "catalogId" bigint GENERATED BY DEFAULT AS IDENTITY,
  ADD COLUMN "rating" double precision GENERATED ALWAYS AS (
    hayer_discovery_rating("snapshot"::jsonb -> 'rating')
  ) STORED,
  ADD COLUMN "review_count" bigint GENERATED ALWAYS AS (
    hayer_discovery_review_count("snapshot"::jsonb -> 'reviewCount')
  ) STORED,
  ADD COLUMN "price_level" smallint GENERATED ALWAYS AS (
    hayer_discovery_price_level("snapshot"::jsonb -> 'priceLevel')
  ) STORED,
  ADD COLUMN "primary_type" text GENERATED ALWAYS AS (
    CASE
      WHEN jsonb_typeof("snapshot"::jsonb -> 'primaryType') = 'string'
        AND length(btrim("snapshot"::jsonb ->> 'primaryType')) BETWEEN 1 AND 200
      THEN btrim("snapshot"::jsonb ->> 'primaryType')
      ELSE NULL
    END
  ) STORED,
  ADD COLUMN "primary_type_key" text GENERATED ALWAYS AS (
    CASE
      WHEN jsonb_typeof("snapshot"::jsonb -> 'primaryType') = 'string'
        AND length(btrim("snapshot"::jsonb ->> 'primaryType')) BETWEEN 1 AND 200
      THEN hayer_discovery_normalize("snapshot"::jsonb ->> 'primaryType')
      ELSE NULL
    END
  ) STORED,
  ADD COLUMN "opening_hours" int4multirange GENERATED ALWAYS AS (
    hayer_discovery_opening_hours("snapshot"::jsonb -> 'hours')
  ) STORED,
  ADD COLUMN "lifecycle_status" text GENERATED ALWAYS AS (
    CASE
      WHEN lower(regexp_replace(btrim(COALESCE("snapshot"::jsonb ->> 'statusText', '')), '\s+', ' ', 'g'))
        LIKE '%permanently closed%'
        OR lower(regexp_replace(btrim(COALESCE("snapshot"::jsonb ->> 'statusText', '')), '\s+', ' ', 'g'))
          LIKE '%مغلق نهائي%'
        OR lower(regexp_replace(btrim(COALESCE("snapshot"::jsonb ->> 'statusText', '')), '\s+', ' ', 'g'))
          LIKE '%مغلق دائم%'
      THEN 'permanently_closed'
      WHEN lower(regexp_replace(btrim(COALESCE("snapshot"::jsonb ->> 'statusText', '')), '\s+', ' ', 'g'))
        LIKE '%temporarily closed%'
        OR lower(regexp_replace(btrim(COALESCE("snapshot"::jsonb ->> 'statusText', '')), '\s+', ' ', 'g'))
          LIKE '%مغلق مؤقت%'
      THEN 'temporarily_closed'
      ELSE 'unknown'
    END
  ) STORED,
  ADD COLUMN "completeness_mask" smallint GENERATED ALWAYS AS (
    (CASE
      WHEN jsonb_typeof("snapshot"::jsonb -> 'photoUrls') = 'array'
        AND jsonb_array_length("snapshot"::jsonb -> 'photoUrls') > 0 THEN 1
      ELSE 0
    END)
    + (CASE
      WHEN hayer_discovery_opening_hours("snapshot"::jsonb -> 'hours') IS NOT NULL THEN 2
      ELSE 0
    END)
    + (CASE
      WHEN jsonb_typeof("snapshot"::jsonb -> 'phoneNumber') = 'string'
        AND length(btrim("snapshot"::jsonb ->> 'phoneNumber')) > 0 THEN 4
      ELSE 0
    END)
    + (CASE
      WHEN jsonb_typeof("snapshot"::jsonb -> 'websiteUrl') = 'string'
        AND length(btrim("snapshot"::jsonb ->> 'websiteUrl')) > 0 THEN 8
      ELSE 0
    END)
    + (CASE
      WHEN hayer_discovery_price_level("snapshot"::jsonb -> 'priceLevel') IS NOT NULL THEN 16
      ELSE 0
    END)
    + (CASE
      WHEN jsonb_typeof("snapshot"::jsonb -> 'editorialSummary') = 'string'
        AND length(btrim("snapshot"::jsonb ->> 'editorialSummary')) > 0 THEN 32
      ELSE 0
    END)
  ) STORED,
  ADD COLUMN "search_text" text GENERATED ALWAYS AS (
    hayer_discovery_normalize(
      "normalizedName" || ' ' ||
      CASE
        WHEN jsonb_typeof("snapshot"::jsonb -> 'editorialSummary') = 'string'
        THEN "snapshot"::jsonb ->> 'editorialSummary'
        ELSE ''
      END
    )
  ) STORED;

CREATE UNIQUE INDEX "hayer_poi_catalog_id"
  ON "hayer_poi_catalog" ("catalogId");
-- The recorded Discover plans never used single-column btrees on rating, review
-- count, price, type or first-seen time: every sort ranks the whole eligible
-- viewport. Those candidates are omitted to keep catalog upserts cheap; the
-- GiST location index and the trigram search index remain.
CREATE INDEX "hayer_discovery_search_trgm"
  ON "hayer_poi_catalog" USING gin ("search_text" gin_trgm_ops)
  WHERE "quarantinedAt" IS NULL;

--
-- MIGRATION VERSION FOR hayer
--
INSERT INTO "serverpod_migrations" ("module", "version", "timestamp")
    VALUES ('hayer', '20260914142952104-discovery-catalog-query', now())
    ON CONFLICT ("module")
    DO UPDATE SET "version" = '20260914142952104-discovery-catalog-query', "timestamp" = now();

--
-- MIGRATION VERSION FOR serverpod
--
INSERT INTO "serverpod_migrations" ("module", "version", "timestamp")
    VALUES ('serverpod', '20260129180959368', now())
    ON CONFLICT ("module")
    DO UPDATE SET "version" = '20260129180959368', "timestamp" = now();

--
-- MIGRATION VERSION FOR serverpod_auth_idp
--
INSERT INTO "serverpod_migrations" ("module", "version", "timestamp")
    VALUES ('serverpod_auth_idp', '20260213194423028', now())
    ON CONFLICT ("module")
    DO UPDATE SET "version" = '20260213194423028', "timestamp" = now();

--
-- MIGRATION VERSION FOR serverpod_auth_core
--
INSERT INTO "serverpod_migrations" ("module", "version", "timestamp")
    VALUES ('serverpod_auth_core', '20260129181112269', now())
    ON CONFLICT ("module")
    DO UPDATE SET "version" = '20260129181112269', "timestamp" = now();


COMMIT;
